-- POINT QUERY (WITHOUT INDEX)
SELECT MAX(BALANCE) FROM CUSTOMERS;
SELECT * FROM CUSTOMERS WHERE BALANCE = 102127;

-- RANGE QUERY (WITHOUT INDEX)
SELECT * FROM CUSTOMERS WHERE MONTH LIKE '%JU%';

-- SCAN QUERY (WITHOUT INDEX)
SELECT MONTH, COUNT(*) AS CUSTOMERS_CONTACTED FROM CUSTOMERS GROUP BY MONTH;

-- QUERY TO TEST DATABASE PERFORMANCE WITH PARTITIONING
SELECT CUSTOMER_ID, RESULTS FROM CUSTOMERS WHERE AGE = 35;

-- QUERY TO TEST PARALLEL EXECUTION
SELECT CUSTOMER_ID, BALANCE, RESULTS, JOB_TYPE
FROM CUSTOMERS
JOIN JOBS USING (JOB_CODE)
JOIN JOB_TYPE USING (JOB_TYPE_CODE)
WHERE AGE BETWEEN 30 AND 50 AND BALANCE >= 10000;
